package routes

import (
	"github.com/albukhary/student-book-course/api_gateway/handlers"

	swagger "github.com/arsmn/fiber-swagger/v2"
	"github.com/gofiber/fiber/v2"

	// docs are generated by Swag CLI, you have to import them.
	_ "github.com/albukhary/student-book-course/api_gateway/docs"
)

func SetUpRoutes(app *fiber.App) {
	app.Get("/swagger/*", swagger.Handler)

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Assalamu alaykum 👋!")
	})
	// Student Related
	app.Post("/create/student", handlers.CreateStudent)
	app.Get("/students", handlers.GetStudents)
	app.Get("/student/:id", handlers.GetStudent)
	app.Delete("/delete/student/:id", handlers.DeleteStudent)
	app.Put("/update/student/:id", handlers.UpdateStudent)

	// Student Book related
	app.Post("/student/borrow/book", handlers.BorrowBook)
	app.Get("/books/student/:id", handlers.GetBorrowedBooks)
	app.Delete("/student/handin/book", handlers.HandInBook)

	// Student Course Related
	app.Post("/student/enroll/course", handlers.EnrollCourse)
	app.Delete("/student/drop/course", handlers.DropCourse)
	app.Get("/courses/student/:id", handlers.GetEnrolledCourses)

	// Book Service related
	app.Post("/create/book", handlers.CreateBook)
	app.Put("/update/book", handlers.UpdateBook)
	app.Get("/book/:id", handlers.GetBook)
	app.Get("/books", handlers.GetAllBooks)
	app.Get("/students/book/:id", handlers.GetBorrowingStudents)
	app.Delete("/delete/book/:id", handlers.DeleteBook)

	// Course Service related
	app.Post("/create/course", handlers.CreateCourse)
	app.Put("/update/course", handlers.UpdateCourse)
	app.Get("/course/:id", handlers.GetCourse)
	app.Get("/courses", handlers.GetAllCourses)
	app.Get("/students/course/:id", handlers.GetEnrolledStudents)
	app.Delete("/delete/course/:id", handlers.DeleteCourse)
}
