definitions:
  model.Book:
    properties:
      author:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
  model.Course:
    properties:
      course_id:
        type: integer
      instructor:
        type: string
      title:
        type: string
    type: object
  model.CreateBookModel:
    properties:
      author:
        type: string
      title:
        type: string
    type: object
  model.CreateCourseModel:
    properties:
      instructor:
        type: string
      title:
        type: string
    type: object
  model.CreateStudentModel:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
    type: object
  model.Student:
    properties:
      email:
        type: string
      first_Name:
        type: string
      id:
        type: integer
      last_Name:
        type: string
    type: object
  model.Student_Book_Ids:
    properties:
      book_id:
        type: integer
      student_id:
        type: integer
    type: object
  model.Student_Course_Ids:
    properties:
      course_id:
        type: integer
      student_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /book/{id}:
    get:
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: Gets details of the Book from User input book ID
      tags:
      - Book Related
  /books:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
      summary: Gets the list of all the books
      tags:
      - Book Related
  /books/student/{id}:
    get:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
      summary: Retrieves the borrowed books of the student based on given ID
      tags:
      - Student Book Related
  /course/{id}:
    get:
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Course'
      summary: Gets details of the Course from User input book ID
      tags:
      - Course Related
  /courses:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Course'
            type: array
      summary: Gets the list of all the courses
      tags:
      - Course Related
  /courses/student/{id}:
    get:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Course'
            type: array
      summary: Retrieves the enrolled courses of the student based on given ID
      tags:
      - Student Course Related
  /create/book:
    post:
      consumes:
      - application/json
      parameters:
      - description: Book details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.CreateBookModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: Creates a Book record with user input details and writes into database
      tags:
      - Book Related
  /create/course:
    post:
      consumes:
      - application/json
      parameters:
      - description: Course details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.CreateCourseModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Course'
      summary: Creates a Course record with user input details and writes into database
      tags:
      - Course Related
  /create/student:
    post:
      consumes:
      - application/json
      parameters:
      - description: Student details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.CreateStudentModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Student'
      summary: Creates a student record with user input details and writes into database
      tags:
      - Student Related
  /delete/book/{id}:
    delete:
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: Deletes the book with the given ID
      tags:
      - Book Related
  /delete/course/{id}:
    delete:
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Course'
      summary: Deletes the course with the given ID
      tags:
      - Course Related
  /delete/student/{id}:
    delete:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Student'
      summary: Deletes a student with the specified ID
      tags:
      - Student Related
  /student/{id}:
    get:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Student'
      summary: Retrieves user based on given ID
      tags:
      - Student Related
  /student/borrow/book:
    post:
      consumes:
      - application/json
      parameters:
      - description: Book and Student IDs
        in: body
        name: student_book_ids
        required: true
        schema:
          $ref: '#/definitions/model.Student_Book_Ids'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: Borrows the book of a given Id for a given student ID
      tags:
      - Student Book Related
  /student/drop/course:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Student and Course IDs
        in: body
        name: student_course_ids
        required: true
        schema:
          $ref: '#/definitions/model.Student_Course_Ids'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Course'
      summary: Drop the student of the given Id from the given course(ID)
      tags:
      - Student Course Related
  /student/enroll/course:
    post:
      consumes:
      - application/json
      parameters:
      - description: Student and Course IDs
        in: body
        name: student_course_ids
        required: true
        schema:
          $ref: '#/definitions/model.Student_Course_Ids'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Course'
      summary: Enrolls the student of the given Id to the given course ID
      tags:
      - Student Course Related
  /student/handin/book:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Book and Student IDs
        in: body
        name: student_book_ids
        required: true
        schema:
          $ref: '#/definitions/model.Student_Book_Ids'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: Hands in the book of a given Id for a given student ID
      tags:
      - Student Book Related
  /students:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Student'
            type: array
      summary: Retrieves the list of all students
      tags:
      - Student Related
  /students/book/{id}:
    get:
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Student'
            type: array
      summary: Gets the list of all students who borrowed a particular book
      tags:
      - Book Related
  /students/course/{id}:
    get:
      parameters:
      - description: Course ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Student'
            type: array
      summary: Gets the list of all students who are enrolled to a particular course
      tags:
      - Course Related
  /update/book:
    put:
      consumes:
      - application/json
      parameters:
      - description: Book details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
      summary: Updates the book record with user input details
      tags:
      - Book Related
  /update/course:
    put:
      consumes:
      - application/json
      parameters:
      - description: Course details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Course'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Course'
      summary: Updates the course record with user input details
      tags:
      - Course Related
  /update/student/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Updated Student Details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/model.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Student'
      summary: Updates a student record with user input details and writes into database
      tags:
      - Student Related
swagger: "2.0"
