definitions:
  main.Book:
    properties:
      author:
        type: string
      bookId:
        type: integer
      title:
        type: string
    type: object
  main.Course:
    properties:
      courseId:
        type: integer
      instructor:
        type: string
      title:
        type: string
    type: object
  main.Student:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
    type: object
  main.Student_Book_Ids:
    properties:
      book_id:
        type: integer
      student_id:
        type: integer
    type: object
  main.Student_Course_Ids:
    properties:
      course_id:
        type: integer
      student_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /books/student/{id}:
    get:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Book'
            type: array
      summary: Retrieves the borrowed books of the student based on given ID
      tags:
      - Book Related
  /courses/student/{id}:
    get:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Course'
            type: array
      summary: Retrieves the enrolled courses of the student based on given ID
      tags:
      - Course Related
  /create/book:
    post:
      consumes:
      - application/json
      parameters:
      - description: Book details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/main.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Book'
      summary: Creates a Book record with user input details and writes into database
      tags:
      - Book Related
  /create/student:
    post:
      consumes:
      - application/json
      parameters:
      - description: Student details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/main.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Student'
      summary: Creates a student record with user input details and writes into database
      tags:
      - Student Related
  /delete/student/{id}:
    delete:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Student'
      summary: Deletes a student with the specified ID
      tags:
      - Student Related
  /student/{id}:
    get:
      parameters:
      - description: Student ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Student'
      summary: Retrieves user based on given ID
      tags:
      - Student Related
  /student/borrow/book:
    post:
      consumes:
      - application/json
      parameters:
      - description: Book and Student IDs
        in: body
        name: student_book_ids
        required: true
        schema:
          $ref: '#/definitions/main.Student_Book_Ids'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Book'
      summary: Borrows the book of a given Id for a given student ID
      tags:
      - Book Related
  /student/drop/course:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Student and Course IDs
        in: body
        name: student_course_ids
        required: true
        schema:
          $ref: '#/definitions/main.Student_Course_Ids'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Course'
      summary: Drop the student of the given Id from the given course(ID)
      tags:
      - Course Related
  /student/enroll/course:
    post:
      consumes:
      - application/json
      parameters:
      - description: Student and Course IDs
        in: body
        name: student_course_ids
        required: true
        schema:
          $ref: '#/definitions/main.Student_Course_Ids'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Course'
      summary: Enrolls the student of the given Id to the given course ID
      tags:
      - Course Related
  /student/handin/book:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Book and Student IDs
        in: body
        name: student_book_ids
        required: true
        schema:
          $ref: '#/definitions/main.Student_Book_Ids'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Book'
      summary: Hands in the book of a given Id for a given student ID
      tags:
      - Book Related
  /students:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Student'
            type: array
      summary: Retrieves the list of all students
      tags:
      - Student Related
  /update/student/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Updated Student Details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/main.Student'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Student'
      summary: Updates a student record with user input details and writes into database
      tags:
      - Student Related
swagger: "2.0"
